### ISSUE TITLE
jetstream version still v0.1.3 breeze version v0.3.0

### ISSUE THREAD

**Issue by mai1237** [Kamona-WD/kui-laravel-jetstream#3]
jetstream version still v0.1.3 breeze version v0.3.0
jetstream version iss stalled ?

**Comment by Kamona-WD** [comment]
It will be updated soon and will also support vitejs.

**Comment by Kamona-WD** [comment]
This package now works with `vitejs` and `laravel-mix`.
Also some styles changed.
If you find any broken thing please open an issue.
